spring:
  application:
    name: turing-collab
    upload:
      dir: static/uploads
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
  datasource:
    url: jdbc:postgresql://db_turing_collab:5432/turing-collab
    username: turing-collab
    password: turing-collab123
