spring:
  application:
    name: turing-collab
    upload:
      dir: static/uploads
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
  datasource:
    url: jdbc:postgresql://localhost:5438/postgres
    username: postgres
    password: 1234
